[package]
name = "day07"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "day07_part1"

[[bin]]
name = "day07_part2"


[dependencies]
rust-embed = "6"
regex = "1,<2"
log = "0,<1"
pretty_env_logger = "0,<1"