[package]
name = "day07"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "day07_part1"

[[bin]]
name = "day07_part2"


[dependencies]
rust-embed = "6.6"
lazy_static = "1.4.0"
regex = "1.7.1"
log = "0.4"
pretty_env_logger = "0.4"