[package]
name = "day16"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "day16_part1"

[[bin]]
name = "day16_part2"

[dependencies]
regex = "1,<2"
rust-embed = "6,<7"
log = "0,<1"
pretty_env_logger = "0,<1"
