[package]
name = "day16"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "day16_part1"

# [[bin]]
# name = "day16_part2"

[dependencies]
regex = "1.9.1"
rust-embed = "6.6"
log = "0.4"
pretty_env_logger = "0.4"
